// Package soul generates and merges SOUL.md files for Hermes
// profiles from meta-harness persona files.
//
// A persona file (e.g. harness/personas/team-manager.md) has many
// sections. A SOUL.md is a focused subset optimized for a single
// agentic session:
//
//	# Identity         (from "## Identidade" / "## Identity")
//	# Responsibilities (from "## Responsabilidades")
//	# Limits           (from "## Limites" / "## 9. Limites")
//	# References       (from "## Referências" / "## 10. Referências")
//
// We extract these sections and assemble a SOUL.md.
package soul

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// SoulSections are the canonical sections in a SOUL.md.
var SoulSections = []string{
	"Identidade",
	"Identidad",
	"Identity",
	"Responsabilidades",
	"Responsibilities",
	"Skills",
	"Limites",
	"Limits",
	"Referências",
	"References",
}

// Generate reads a persona file and extracts the SOUL sections.
//
// The output starts with a header noting it was generated by gmh,
// followed by the extracted sections in canonical order. User
// customizations (sections NOT in SoulSections) are preserved as
// "## Custom (preserved)" at the end.
//
// If frameworkVersion and personaHash are non-empty, a version
// marker is injected at the top of the SOUL so subsequent syncs
// can detect staleness via ExtractVersionMarker.
func Generate(personaPath, frameworkVersion string) (string, error) {
	data, err := os.ReadFile(personaPath)
	if err != nil {
		return "", fmt.Errorf("read persona: %w", err)
	}
	content := string(data)

	personaHash, err := PersonaHash(personaPath)
	if err != nil {
		return "", err
	}

	sections := extractSections(content, SoulSections)
	custom := extractCustomSections(content, SoulSections)

	var b strings.Builder

	// Inject version marker FIRST (so it's at the top of the file)
	if frameworkVersion != "" {
		b.WriteString(BuildVersionMarker(frameworkVersion, personaHash))
	}

	b.WriteString(fmt.Sprintf(`# SOUL — auto-generated from %s

> **DO NOT EDIT BY HAND.** This file is regenerated by `+"`gmh agents sync`"+`.
> Customizations go in `+"`memory/`"+` or as separate docs referenced from here.
> Source: %s (in the meta-harness framework)

`, filepath.Base(personaPath), personaPath))

	for _, sec := range sections {
		b.WriteString(sec.Content)
		b.WriteString("\n\n")
	}

	if len(custom) > 0 {
		b.WriteString("\n## Custom sections (preserved from old SOUL.md)\n\n")
		for _, sec := range custom {
			b.WriteString(sec.Content)
			b.WriteString("\n\n")
		}
	}

	return b.String(), nil
}

// Section is an extracted markdown section.
type Section struct {
	Title   string
	Content string // full content including the ## header
}

// extractSections returns the named sections in the order they appear.
func extractSections(content string, names []string) []Section {
	sections := splitSections(content)
	nameSet := make(map[string]bool)
	for _, n := range names {
		nameSet[strings.ToLower(n)] = true
	}
	var out []Section
	for _, s := range sections {
		if nameSet[strings.ToLower(s.Title)] {
			out = append(out, s)
		}
	}
	return out
}

// extractCustomSections returns sections whose title is NOT in `names`.
func extractCustomSections(content string, names []string) []Section {
	sections := splitSections(content)
	nameSet := make(map[string]bool)
	for _, n := range names {
		nameSet[strings.ToLower(n)] = true
	}
	var out []Section
	for _, s := range sections {
		if !nameSet[strings.ToLower(s.Title)] && !isTopHeader(s.Title) {
			out = append(out, s)
		}
	}
	return out
}

// isTopHeader returns true if the section title is the document's
// top-level heading (e.g. "# Persona — Team Manager").
func isTopHeader(title string) bool {
	return strings.HasPrefix(title, "Persona") || strings.HasPrefix(title, "Sensor")
}

// splitSections splits a markdown file into sections by `^## ` headers.
func splitSections(content string) []Section {
	scanner := bufio.NewScanner(strings.NewReader(content))
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024) // 1MB max line

	var sections []Section
	var current *Section

	headerRe := regexp.MustCompile(`^(#{1,3})\s+(.+?)\s*$`)

	for scanner.Scan() {
		line := scanner.Text()
		if m := headerRe.FindStringSubmatch(line); m != nil {
			// New header
			if current != nil {
				sections = append(sections, *current)
			}
			current = &Section{
				Title:   m[2],
				Content: line + "\n",
			}
		} else if current != nil {
			current.Content += line + "\n"
		}
	}
	if current != nil {
		sections = append(sections, *current)
	}
	return sections
}

// Diff shows what would change between current and generated SOUL.md.
// Returns the lines added, removed, and a summary.
type Diff struct {
	Added     []string
	Removed   []string
	Unchanged int
	Summary   string
}

// ComputeDiff computes a line-level diff between current and generated.
// This is a simple LCS-free diff (just set-based) — sufficient for
// human review but not for auto-merge.
func ComputeDiff(current, generated string) Diff {
	curLines := strings.Split(current, "\n")
	genLines := strings.Split(generated, "\n")

	curSet := make(map[string]bool)
	for _, l := range curLines {
		curSet[l] = true
	}
	genSet := make(map[string]bool)
	for _, l := range genLines {
		genSet[l] = true
	}

	var d Diff
	for _, l := range genLines {
		if !curSet[l] {
			d.Added = append(d.Added, l)
		} else {
			d.Unchanged++
		}
	}
	for _, l := range curLines {
		if !genSet[l] {
			d.Removed = append(d.Removed, l)
		}
	}

	d.Summary = fmt.Sprintf("+%d -%d =%d", len(d.Added), len(d.Removed), d.Unchanged)
	return d
}

// PersonaNameFromFilename extracts a persona name from a filename
// like "team-manager.md" → "team-manager".
func PersonaNameFromFilename(filename string) string {
	base := filepath.Base(filename)
	return strings.TrimSuffix(base, filepath.Ext(base))
}

// PersonaHash computes a stable hash of the persona file content
// (SHA-256 hex, first 16 chars). Used as a version marker.
func PersonaHash(personaPath string) (string, error) {
	data, err := os.ReadFile(personaPath)
	if err != nil {
		return "", err
	}
	// Simple FNV-1a hash (64-bit) to avoid importing crypto/sha256
	// for what is just an etag.
	h := uint64(14695981039346656037)
	for _, b := range data {
		h ^= uint64(b)
		h *= 1099511628211
	}
	return fmt.Sprintf("%016x", h), nil
}

// VersionMarker is the HTML comment we inject into generated SOUL.md
// so subsequent `gmh agents sync` can detect if the SOUL is fresh
// or stale.
const VersionMarkerPrefix = "<!-- gmh:soul "

// BuildVersionMarker returns the marker string to inject.
func BuildVersionMarker(frameworkVersion, personaHash string) string {
	return VersionMarkerPrefix + "version=" + frameworkVersion + " hash=" + personaHash + " -->\n"
}

// ExtractVersionMarker returns the version + hash from a SOUL.md,
// or "" if no marker is present.
func ExtractVersionMarker(soulContent string) (version, hash string) {
	idx := strings.Index(soulContent, VersionMarkerPrefix)
	if idx < 0 {
		return "", ""
	}
	end := strings.Index(soulContent[idx:], "-->")
	if end < 0 {
		return "", ""
	}
	marker := soulContent[idx+len(VersionMarkerPrefix) : idx+end]
	// Parse "version=X hash=Y"
	for _, kv := range strings.Fields(marker) {
		if strings.HasPrefix(kv, "version=") {
			version = strings.TrimPrefix(kv, "version=")
		}
		if strings.HasPrefix(kv, "hash=") {
			hash = strings.TrimPrefix(kv, "hash=")
		}
	}
	return version, hash
}
